#Made by BGHDNetwork(Noodles)
#=======================================================
#Plugin Page: https://www.spigotmc.org/resources/20392/
#=======================================================
Update:
  Enabled: true
#tntblockdamage.update
#Enables if there is a message on-join when the plugin is outdated.
#=======================================================
CheckForUpdates:
  Enabled: true
#Enables a message in console if the plugin is outdated.
#=======================================================
#Plugin Commands:
# /tnt - tntblockdamage.use
