name: TNTBlockDamage
version: ${project.version}
main: me.noodles.tntblockdamage.TNTBlockDamage
authors: [BGHDDevelopment]
website: https://bghddevelopment.com/
commands:
  tnt:
    description: Launch TNT where you are looking
    usage: /<command>